// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzSZFYgYahmvyqWtNWdOESrUMSJhaIGwk',
    appId: '1:283282058516:web:1ea122b04a95bd43bf2601',
    messagingSenderId: '283282058516',
    projectId: 'projectapp-3b56f',
    authDomain: 'projectapp-3b56f.firebaseapp.com',
    storageBucket: 'projectapp-3b56f.firebasestorage.app',
    measurementId: 'G-BYKGXD9TPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk1SIbFbeKWAl9D57qQKTCXDLsjNsFgl4',
    appId: '1:283282058516:android:c74e3a7224825df0bf2601',
    messagingSenderId: '283282058516',
    projectId: 'projectapp-3b56f',
    storageBucket: 'projectapp-3b56f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj7_fkxKGYOoqVO2uC6j8aoOT2AtiFZBg',
    appId: '1:283282058516:ios:cb173e8d6ad7f713bf2601',
    messagingSenderId: '283282058516',
    projectId: 'projectapp-3b56f',
    storageBucket: 'projectapp-3b56f.firebasestorage.app',
    iosBundleId: 'com.example.pjApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj7_fkxKGYOoqVO2uC6j8aoOT2AtiFZBg',
    appId: '1:283282058516:ios:cb173e8d6ad7f713bf2601',
    messagingSenderId: '283282058516',
    projectId: 'projectapp-3b56f',
    storageBucket: 'projectapp-3b56f.firebasestorage.app',
    iosBundleId: 'com.example.pjApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzSZFYgYahmvyqWtNWdOESrUMSJhaIGwk',
    appId: '1:283282058516:web:8b72530e3c5a6041bf2601',
    messagingSenderId: '283282058516',
    projectId: 'projectapp-3b56f',
    authDomain: 'projectapp-3b56f.firebaseapp.com',
    storageBucket: 'projectapp-3b56f.firebasestorage.app',
    measurementId: 'G-FCPMW3TTRT',
  );
}
